services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - mern-network
  mern-server:
    build: ./server
    container_name: mern-server
    networks:
      - mern-network
    ports:
      - 5001:5000
    depends_on:
      - mongodb
  mern-blog-frontend:
    build: ./client
    container_name: mern-blog-frontend
    networks:
      - mern-network
    ports:
      - 3001:80
    depends_on:
      - mern-server
volumes:
  mongodb_data:
networks:
  mern-network:
    driver: bridge
